version: '2'
services:
  omar-service-proxy-app:
    # networks:
    #   - docker_default
    image: omar-service-proxy-app:latest
    volumes:
      - /dev/urandom:/dev/random
      # - /home:/home
      # - /Users:/Users
    ports:
      - "8080:8080"
networks:
  default:
    external:
      name: docker_default
